CREATE TABLE recibo_caja_detalle (
  rcd_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rc_num BIGINT UNSIGNED NOT NULL,
  pla_id BIGINT UNSIGNED NOT NULL,
  rcd_cantidad SMALLINT UNSIGNED NOT NULL,
  rcd_precio DECIMAL(10,2) NOT NULL,
  rcd_descuento DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (rcd_id),
  KEY fk_rcd_recibo (rc_num),
  KEY fk_rcd_plato (pla_id),
  CONSTRAINT fk_rcd_recibo FOREIGN KEY (rc_num) REFERENCES recibo_caja(rc_num) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_rcd_plato FOREIGN KEY (pla_id) REFERENCES plato(pla_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
