CREATE TABLE sede (
  sede_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sede_nombre VARCHAR(120) NOT NULL,
  sede_direccion VARCHAR(200) DEFAULT NULL,
  sede_telefono VARCHAR(30) DEFAULT NULL,
  sede_estado ENUM('ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (sede_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
