CREATE TABLE IF NOT EXISTS area_mesa (
  area_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sede_id BIGINT UNSIGNED NOT NULL,
  area_nombre VARCHAR(100) NOT NULL,
  area_estado ENUM('ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (area_id),
  KEY fk_area_sede (sede_id),
  CONSTRAINT fk_area_sede FOREIGN KEY (sede_id)
    REFERENCES sede(sede_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
