CREATE TABLE IF NOT EXISTS mesa (
  mesa_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sede_id BIGINT UNSIGNED NOT NULL,
  area_id BIGINT UNSIGNED DEFAULT NULL,
  mesa_numero VARCHAR(10) NOT NULL,
  capacidad TINYINT UNSIGNED NOT NULL DEFAULT 4,
  x_pos INT NOT NULL DEFAULT 0,
  y_pos INT NOT NULL DEFAULT 0,
  estado ENUM('DISPONIBLE','OCUPADA','RESERVADA','INACTIVA') NOT NULL DEFAULT 'DISPONIBLE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (mesa_id),
  UNIQUE KEY uk_mesa_sede (mesa_numero, sede_id),
  KEY fk_mesa_sede (sede_id),
  KEY fk_mesa_area (area_id),
  CONSTRAINT fk_mesa_sede FOREIGN KEY (sede_id)
    REFERENCES sede(sede_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_mesa_area FOREIGN KEY (area_id)
    REFERENCES area_mesa(area_id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
