CREATE TABLE IF NOT EXISTS categoria_plato (
  cat_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cat_nombre VARCHAR(100) NOT NULL,
  cat_imagen VARCHAR(255) DEFAULT NULL,
  cat_estado TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (cat_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
