CREATE TABLE IF NOT EXISTS presentacion (
  pres_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pres_descripcion VARCHAR(50) NOT NULL,
  pres_abreviatura VARCHAR(10) NOT NULL,
  pres_estado ENUM('ACTIVO','INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (pres_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
