CREATE TABLE IF NOT EXISTS categoria_insumo (
  cins_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cins_nombre VARCHAR(100) NOT NULL,
  cins_imagen VARCHAR(255) DEFAULT NULL,
  cins_estado TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (cins_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
