CREATE TABLE IF NOT EXISTS configuracion (
  cfg_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cfg_clave VARCHAR(100) NOT NULL,
  cfg_valor TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (cfg_id),
  UNIQUE KEY uk_cfg_clave (cfg_clave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
